server:
  port: 8080
spring:
  application:
    name: hs-blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hs_blog?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456